export const AUTH_REQUESTED = "AUTH_REQUESTED"
export const AUTH_RECEIVED = "AUTH_RECEIVED"
export const LOGOUT_REQUESTED = "LOGOUT_REQUESTED"
export const LOGOUT_RECEIVED = "LOGOUT_RECEIVED"
export const SESSION_RESTORE_REQUESTED = 'SESSION_RESTORE_REQUESTED'
export const SESSION_RESTORE_RECEIVED = 'SESSION_RESTORE_RECEIVED'
